name: Build and Push App to DockerHub 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Copy my code to github machine 
        uses: actions/checkout@v4 
      
      - name: Build Docker Contianer  
        run: docker build -t app-go . 

      - name: login to docker hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }}| docker login -u ahmedshams8 --password-stdin

      - name: push the image to docker hub 
        run : docker push ahmedshams8/app-go:latest 
