name: Build and Push App to DockerHub 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Copy my code to github machine 
        uses: actions/checkout@v4 
      
      - name: Build Docker Contianer  
        run: docker build -t app-go . 


